from __future__ import annotations

import logging
import io

from aiogram import F, Router
from aiogram.enums import ChatAction
from aiogram.types import Message

from app.services.chat_service import ChatService

logger = logging.getLogger(__name__)

_TG_MAX_LENGTH: int = 4096
_SAFE_SLICE: int = 4000

chat_router = Router(name="chat")

from aiogram.filters import Command, CommandObject
from aiogram.types import BufferedInputFile

@chat_router.message(Command("image"))
async def cmd_image(message: Message, command: CommandObject, chat_service: ChatService) -> None:
    """Generate an image using the VIP engine."""
    if not command.args:
        await message.answer("⚠️ Please provide a description. Example:\n<code>/image A futuristic neon city</code>", parse_mode="HTML")
        return

    try:
        await message.bot.send_chat_action(chat_id=message.chat.id, action=ChatAction.UPLOAD_PHOTO)
        
        result = await chat_service.generate_image_for_user(
            telegram_id=message.from_user.id,
            prompt=command.args
        )

        if isinstance(result, str):
            # It's an error message
            await message.answer(result, parse_mode="HTML")
        else:
            # It's image bytes
            photo = BufferedInputFile(result, filename="generated.jpg")
            await message.answer_photo(
                photo=photo,
                caption=f"🎨 <b>Generated by Nano Banana 2</b>\n\n<i>Prompt:</i> {command.args}",
                parse_mode="HTML"
            )
            
    except Exception as e:
        logger.error("Error in image handler: %s", e, exc_info=True)
        await message.answer("⚠️ An unexpected error occurred.", parse_mode=None)
@chat_router.message(F.photo)
async def handle_photo_message(message: Message, chat_service: ChatService) -> None:
    if message.from_user is None or not message.photo:
        return

    try:
        await message.bot.send_chat_action(chat_id=message.chat.id, action=ChatAction.TYPING)
        
        photo = message.photo[-1]
        buffer = io.BytesIO()
        await message.bot.download(photo, destination=buffer)
        media_bytes = buffer.getvalue()

        text = message.caption or "Please describe this image."

        ai_reply: str = await chat_service.process_user_message(
            telegram_id=message.from_user.id,
            username=message.from_user.username,
            first_name=message.from_user.first_name,
            text=text,
            media_bytes=media_bytes,
            mime_type="image/jpeg",
        )

        if len(ai_reply) > _TG_MAX_LENGTH:
            ai_reply = ai_reply[:_SAFE_SLICE] + "\n\n… ✂️ <i>(trimmed)</i>"

        await message.answer(ai_reply, parse_mode="HTML")
        
    except Exception as e:
        logger.error("Error processing photo: %s", e, exc_info=True)
        await message.answer("⚠️ Sorry, an error occurred while processing your image. Please try again.", parse_mode=None)

@chat_router.message(F.document)
async def handle_document_message(message: Message, chat_service: ChatService) -> None:
    if message.from_user is None or not message.document:
        return

    mime_type = message.document.mime_type
    supported_mimes = ["application/pdf", "text/plain"]
    
    if mime_type not in supported_mimes:
        await message.answer("⚠️ I only support PDF and TXT files at the moment.")
        return

    # Check file size (e.g., limit to 5MB to avoid memory/timeout issues for MVP)
    if message.document.file_size and message.document.file_size > 5 * 1024 * 1024:
        await message.answer("⚠️ File is too large. Please send a file under 5MB.")
        return

    try:
        await message.bot.send_chat_action(chat_id=message.chat.id, action=ChatAction.TYPING)
        
        buffer = io.BytesIO()
        await message.bot.download(message.document, destination=buffer)
        media_bytes = buffer.getvalue()

        text = message.caption or "Please analyze this document."

        ai_reply: str = await chat_service.process_user_message(
            telegram_id=message.from_user.id,
            username=message.from_user.username,
            first_name=message.from_user.first_name,
            text=text,
            media_bytes=media_bytes,
            mime_type=mime_type,
        )

        if len(ai_reply) > _TG_MAX_LENGTH:
            ai_reply = ai_reply[:_SAFE_SLICE] + "\n\n… ✂️ <i>(trimmed)</i>"

        await message.answer(ai_reply, parse_mode="HTML")
        
    except Exception as e:
        logger.error("Error processing document: %s", e, exc_info=True)
        await message.answer("⚠️ Sorry, an error occurred while processing your file.", parse_mode=None)

@chat_router.message(Command("stats"))
async def cmd_my_stats(message: Message, chat_service: ChatService) -> None:
    """Shows user personal statistics and usage."""
    if message.from_user is None:
        return
        
    user = await chat_service._repo.get_user_by_telegram_id(message.from_user.id)
    if not user:
        return
        
    join_date = user.created_at.strftime('%Y-%m-%d') if user.created_at else "Unknown"
    
    text = (
        "📊 <b>Your Personal Stats</b>\n\n"
        f"🗓 <b>Joined:</b> {join_date}\n"
        f"💬 <b>Normal Credits:</b> {user.normal_credits}\n"
        f"🪙 <b>Premium Credits:</b> {user.premium_credits}\n"
        f"🔗 <b>Referred By:</b> <code>{user.referred_by or 'None'}</code>\n\n"
        f"💡 <i>Tip: Normal credits reset automatically every night!</i>"
    )
    
    await message.answer(text, parse_mode="HTML")

@chat_router.message(F.voice)
async def handle_voice_message(message: Message, chat_service: ChatService) -> None:
    """Handle Telegram voice notes."""
    if message.from_user is None or not message.voice:
        return

    # Check file size (limit to 5MB for quick processing)
    if message.voice.file_size and message.voice.file_size > 5 * 1024 * 1024:
        await message.answer("⚠️ Voice message is too long. Please send a shorter audio clip (under 5MB).")
        return

    try:
        await message.bot.send_chat_action(chat_id=message.chat.id, action=ChatAction.TYPING)
        
        # Download the voice file from Telegram
        buffer = io.BytesIO()
        await message.bot.download(message.voice, destination=buffer)
        media_bytes = buffer.getvalue()

        # Telegram voice notes are OGG format
        mime_type = "audio/ogg"
        text_prompt = "Please listen to this audio and reply to it naturally."

        # Send to Gemini
        ai_reply: str = await chat_service.process_user_message(
            telegram_id=message.from_user.id,
            username=message.from_user.username,
            first_name=message.from_user.first_name,
            text=text_prompt,
            media_bytes=media_bytes,
            mime_type=mime_type,
        )

        if len(ai_reply) > 4000:
            ai_reply = ai_reply[:3900] + "\n\n… ✂️ <i>(trimmed)</i>"

        await message.reply(ai_reply, parse_mode="HTML")
        
    except Exception as e:
        logger.error("Error processing voice: %s", e, exc_info=True)
        await message.answer("⚠️ Sorry, I couldn't process your voice message right now.", parse_mode=None)

@chat_router.message(F.text)
async def handle_text_message(message: Message, chat_service: ChatService) -> None:
    if message.from_user is None or message.text is None:
        return

    try:
        await message.bot.send_chat_action(chat_id=message.chat.id, action=ChatAction.TYPING)
        
        ai_reply: str = await chat_service.process_user_message(
            telegram_id=message.from_user.id,
            username=message.from_user.username,
            first_name=message.from_user.first_name,
            text=message.text,
        )

        if len(ai_reply) > _TG_MAX_LENGTH:
            ai_reply = ai_reply[:_SAFE_SLICE] + "\n\n… ✂️ <i>(trimmed)</i>"

        await message.answer(ai_reply, parse_mode="HTML")
        
    except Exception as e:
        logger.error("Error processing text: %s", e, exc_info=True)
        await message.answer("⚠️ Sorry, an error occurred. Please try again.", parse_mode=None)
